#pragma once

#include <cstdint>

#define ORAM_HEIGHT 5
#define ORAM_BLOCK_SIZE 16
#define ORAM_BUCKET_SIZE 4

// This should be replaced with a random number securely generated by the user at runtime
#define ORAM_RNG_INIT (0x6A510E8A2A376982ull)


// Determines what the main function will do
enum class ProgramMode : uint32_t {
	InitORAM = 0,
	AccessORAM = 1,
	BinaryTreeRead = 2,
	BinaryTreeWrite = 3,
};


void ORAMController(uint32_t program_mode, uint32_t oram_op, uint64_t block_addr, uint8_t* block_data, uint8_t* server_data);
